Import('env')

env.Library("glib-jsonrpc_local",
            ["glib-jsonrpc-json.c",
             "glib-jsonrpc-server.c",
             "glib-jsonrpc-client.c"],
            CPPPATH=["."]+env['CPPPATH'])

SConscript(['json-glib/SConscript'],
           exports='env')
