#+startup: hidestars
* <2010-10-30 Sat>
** Maemo installation
  - Don't install "complex plugins".
  - libpcre3 dependancy.
  - Have to get around vala and gob2 dependancy by adding generated files to git!
  - autoconf is badly broken.
  - Created if's in scons to not run vala or gob2 in sbox.
  - Optify requires:
#+begin_src sh
 cd /usr/lib
 ln -s /opt/maemo/usr/lib/libgiv-image.so 
 cd /usr/bin
 ln -s /opt/maemo/usr/bin/giv
#+end_src

* <2011-12-30 Fri>
** Async commands
   - Something is wrong with async communication as there is no handle to the query but only to the server. What if there are several queries done simultanously. How would the server differentiate between them? *Ok*
* <2012-01-06 Fri>
** Done/Todo
   - [ ] Create a command line tool for windows with a parser like the one included in giv.
* <2012-04-22 Sun>
** Done/Todo
    - Changed the menu checkbuttons to reflect the internal giv-widget states:
      - [X] balloon
      - [X] horizontal-flip
      - [X] vertical-flip
      - [X] show marks
      - [X] cross hair - erased as it doesn't work.
    - Save the following settings:
      - [X] Sub pixel coordinate.
      - [ ] Auto resize.
* <2012-04-27 Fri>
** Done/Todo
   - [X] Recursively turn on and off child nodes when toggling the display of a parent in the model viewer.
   - [X] Why is initial scaling different from the scaling received with "fill"? Due to the sticky autoscale setting. Fixed by forcing fill on initial load of dataset.
* <2012-06-21 Thu>
** Windows 64 bit compilation
   - Need to compile the following libraries as they are not provided by federa:
     - [ ] cfitsio
     - [ ] json-glib
     - [ ] Fix dcm library
*** cfitsio compilation
    - Got sources from http://heasarc.gsfc.nasa.gov/fitsio/
    - Commands:
    #+begin_src sh
   cd ~/src
   tar -xf /tmp/cfitsio3300.tar.gz
   cd cfitsio
   env CC=x86_64-w64-mingw32-gcc ./configure --host=x86_64-w64-mingw32 --prefix=/usr/local/mingw64
   make -j 4
   make install
    #+end_src
   - Even though compilation of cfitsio succeeded linking failed. Need to figure out why. Meanwhile removed fitsio plugin from installation.
   - Get errors like the following:
   #+begin_example
   /usr/lib/gcc/x86_64-w64-mingw32/4.7.0/../../../../x86_64-w64-mingw32/bin/ld: skipping incompatible /usr/local/mingw64/lib/libcfitsio.a when searching for -lcfitsio
   #+end_example
    - Solved fitsio problem by literal inclusion of sources.
