/* Generated by GOB (v2.0.12)   (do not edit directly) */

#ifndef __DOV_IMAGE_VIEWER_PRIVATE_H__
#define __DOV_IMAGE_VIEWER_PRIVATE_H__

#include "dov-image-viewer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _DovImageViewerPrivate {
#line 40 "src/dov_image_viewer/dov-image-viewer.gob"
	GdkPixbuf * image;
#line 41 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble current_scale_x;
#line 42 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble current_scale_y;
#line 43 "src/dov_image_viewer/dov-image-viewer.gob"
	gint current_x0;
#line 44 "src/dov_image_viewer/dov-image-viewer.gob"
	gint current_y0;
#line 45 "src/dov_image_viewer/dov-image-viewer.gob"
	gint canvas_width;
#line 46 "src/dov_image_viewer/dov-image-viewer.gob"
	gint canvas_height;
#line 47 "src/dov_image_viewer/dov-image-viewer.gob"
	gboolean do_flip_vertical;
#line 48 "src/dov_image_viewer/dov-image-viewer.gob"
	gboolean do_flip_horizontal;
#line 49 "src/dov_image_viewer/dov-image-viewer.gob"
	gboolean do_use_transfer_map;
#line 50 "src/dov_image_viewer/dov-image-viewer.gob"
	gboolean do_fill_on_resize;
#line 53 "src/dov_image_viewer/dov-image-viewer.gob"
	gboolean one_shot_block_fill_on_resize;
#line 54 "src/dov_image_viewer/dov-image-viewer.gob"
	GdkInterpType interp_type;
#line 55 "src/dov_image_viewer/dov-image-viewer.gob"
	guint8 * transfer_map[3];
#line 56 "src/dov_image_viewer/dov-image-viewer.gob"
	gboolean do_linear_zoom_steps;
#line 57 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble min_zoom;
#line 58 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble max_zoom;
#line 59 "src/dov_image_viewer/dov-image-viewer.gob"
	GdkGC * gc;
#line 60 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble scroll_min_x;
#line 61 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble scroll_max_x;
#line 62 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble scroll_min_y;
#line 63 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble scroll_max_y;
#line 64 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble scroll_width;
#line 65 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble scroll_height;
#line 66 "src/dov_image_viewer/dov-image-viewer.gob"
	GtkAdjustment * hadjustment;
#line 67 "src/dov_image_viewer/dov-image-viewer.gob"
	GtkAdjustment * vadjustment;
#line 68 "src/dov_image_viewer/dov-image-viewer.gob"
	gint last_x;
#line 69 "src/dov_image_viewer/dov-image-viewer.gob"
	gint last_y;
#line 70 "src/dov_image_viewer/dov-image-viewer.gob"
	gboolean is_mouse_button2_pressed;
#line 71 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble last_pan_anchor_x;
#line 72 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble last_pan_anchor_y;
#line 73 "src/dov_image_viewer/dov-image-viewer.gob"
	gint button;
#line 74 "src/dov_image_viewer/dov-image-viewer.gob"
	GdkDrawable * cache_area;
#line 75 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble cache_scale_x;
#line 76 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble cache_scale_y;
#line 77 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble cache_current_x0;
#line 78 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble cache_current_y0;
#line 79 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble cache_width;
#line 80 "src/dov_image_viewer/dov-image-viewer.gob"
	gdouble cache_height;
#line 81 "src/dov_image_viewer/dov-image-viewer.gob"
	gboolean frozen;
#line 94 "dov-image-viewer-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
