Import('env')

def CheckPKG(context, name):
     context.Message( 'Checking for %s... ' % name )
     ret = context.TryAction('${PKGCONFIG} --exists \'%s\'' % name)[0]
     context.Result( ret )
     return ret
 
libs=['giv-widget','gtkimageviewer_local','aggx','plis','pcrex']
for p in [#'pgm.c',
          'npy.c',
#          'simple_dicom.c'
          ]:
    env.SharedLibrary(p,
                      LIBPATH=['..','../gtkimageviewer','../agg','../pcre','../plis']+env['LIBPATH'],
                      LIBS = ['giv-image']+env['LIBS']
                      )

# Change this to Maemo
if not env['SBOX']:
    # Prefer system fits library if it exists
    conf = Configure(env,
                     custom_tests = { 'CheckPKG' : CheckPKG } )

    if conf.CheckPKG('cfitsio'):
        print "Using system cfitsio library"
        env.ParseConfig('${PKGCONFIG} --cflags --libs cfitsio')

        env.SharedLibrary('fits',
                      ['fits.c'],
                      LIBPATH=['..','../gtkimageviewer','../agg','../pcre','../plis']+env['LIBPATH'],
                      LIBS=['giv-image']+env['LIBS'],
                      CPPPATH= env['CPPPATH']
                      )
    
    plugin_dicom = env.SharedLibrary('dicom',
                      ['dicom.cc'],
                      CPPPATH=['dcmtk/dcmdata/include',
                               'dcmtk/ofstd/include',
                               'dcmtk/config/include',
                               '..'
                               ] + env['CPPPATH'],
                      LIBPATH=['..','#/src/plugins/dcmtk/${ARCHDIR}/${VARIANT}'] + env['LIBPATH']+env['LIBPATH'],
                      LIBS=['dcmdata','ofstd','giv-image']+env['LIBS'])
    env.SharedLibrary('tiff',
                      ['tiff.c'],
                      LIBPATH=['..','../gtkimageviewer','../agg','../pcre','../plis'] + env['LIBPATH'],
                      LIBS=['libtiff','giv-image']+env['LIBS'],
                      )
    env.SharedLibrary('png',
                      ['png.c'],
                      LIBPATH=['..','../gtkimageviewer','../agg','../pcre','../plis'] + env['LIBPATH'],
                      LIBS=['png','z','giv-image']+env['LIBS'],
                      )
    env.Depends(plugin_dicom,
                ['#/src/plugins/dcmtk/${ARCHDIR}/${VARIANT}/libdcmdata.a',
                 '#/src/plugins/dcmtk/${ARCHDIR}/${VARIANT}/libofstd.a'])

    SConscript(['dcmtk/SConscript'],
               exports='env')
